### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by rcsmit** [jcontini/facebook-scraper#10]
Hello, I don't know where to leave a message otherwise (new here at Github), so I do it like this

Thanks for your code, I used it as base to retreive the current cities of my friends :)

https://github.com/rcsmit/friendscurrentcity/tree/master

Kind regards
Rene

**Comment by jcontini** [comment]
Thank you so much for letting me know about this! I've wanted to get
current cities as well, so super happy to see that you've created the
feature! I'll check it out soon. Happy to collaborate on adding more
features in the future.

Cheers,
Joe

**Comment by rcsmit** [comment]
I have put all my code for the project in one branch(?) with some comments: https://github.com/rcsmit/facebookfriendsonmap

Have a nice day!

**Comment by jcontini** [comment]
Hey @rcsmit, wanted to let you know that I also added a mapping function to the latest version. It uses Mapbox on the frontend so no application server or database is needed, though I agree that's a better direction to go in if productizing this. Hope it helps!
