### ISSUE TITLE
UnicodeEncodeError on file writing

### ISSUE THREAD

**Issue by eanon** [jcontini/facebook-scraper#11]
Hello, 

Nice job!

Just got UnicodeEncodeError error everywhere you save a page source on disk. So, I simply changed every:

```with` open (friends_html, 'w') as f:```

to 

```with open (friends_html, 'w', encoding='utf-8') as f:```

[context: Python 3.7 under Windows 7]

**Comment by jcontini** [comment]
Oh thank you! If you're still experiencing the issue, could I ask you to do a pull request? Thanks!

**Comment by eanon** [comment]
"Unfortunately", I don't use your piece of software anymore. Not due to your code, but because I'm not really involved against Facebook and it was just a quick test for a specific need... Then, I cloned, ran and erased ;) Of course, if I use it again later, I'll do it; if you didn't in the meantime. Have a good day!
