### ISSUE TITLE
extract.py error

### ISSUE THREAD

**Issue by camiloandresrc** [jcontini/facebook-scraper#13]
Hi, i'm trying the code in MacOS but when i run python extract.py, the console shows the following error:

![image](https://user-images.githubusercontent.com/28818614/60759771-ec2ec900-9fef-11e9-869a-9e816a458da7.png)

Thanks.

**Comment by jcontini** [comment]
Hey @camiloandresrc, can you try to download the repo again and then run `pipenv install`? I updated the readme to try to be a bit clearer.

**Comment by camiloandresrc** [comment]
Hi @jcontini 

I downloaded the code again and launched 'pipnev install'. This is a screenshot of the console:

![image](https://user-images.githubusercontent.com/28818614/60779122-29ce4780-a0ff-11e9-81bb-c52e74e961a3.png)

continue:

![image](https://user-images.githubusercontent.com/28818614/60779206-6ac65c00-a0ff-11e9-92e8-18ab7ac99e09.png)

So, when I launch 'python extract.py', the following error appears:

![image](https://user-images.githubusercontent.com/28818614/60779298-d3add400-a0ff-11e9-9795-014d18658965.png)

Additionally, could you explain how to create a .env file for pipenv and set the variables?

Thanks.

**Comment by jcontini** [comment]
Hi @camiloandresrc, that error happens when you're using Python 2 instead of 3. Can you try again with Python 3? This is the way I set it up on MacOS: https://docs.python-guide.org/starting/install3/osx/

Also, I've set it up so that on first run, it will generate the .env file for you .
