### ISSUE TITLE
i referenced before assignment in index_friends()

### ISSUE THREAD

**Issue by natejgardner** [jcontini/facebook-scraper#17]
![image](https://user-images.githubusercontent.com/8813777/77868702-013c2f80-71f1-11ea-9853-a1e35d77dc69.png)

**Comment by natejgardner** [comment]
Can be fixed by adding a tab to line 136 and 267 of make.py

**Comment by jcontini** [comment]
Thanks @natejgardner , just fixed this in the latest push. Turns out that Facebook updated the friends list template which was blocking the script from parsing the friends. If you pull the latest script, it should be working for the friend indexing again. Let me know if it doesn't.

**Comment by jcontini** [comment]
Ah, I see how this can still cause some issues. Will fix in next push for both.

**Comment by jcontini** [comment]
Should be fixed now, let me know if you run into it again @natejgardner
