### ISSUE TITLE
local variable 'i' referenced before assignment

### ISSUE THREAD

**Issue by danielp3011** [jcontini/facebook-scraper#19]
While running make.py, after logging in manually, I get this error:

  File "make.py", line 402, in <module>
    index_friends()
  File "make.py", line 136, in index_friends
    print('Indexed %s friends to %s' % (i,db_index))
UnboundLocalError: local variable 'i' referenced before assignment

Hope you can help me.

**Comment by jcontini** [comment]
Hi @danielp3011, that's an old version of the script. That line of code was replaced in the version from 10 days ago to fix that bug. Can you delete & re-download the script from Github?

If you already have profiles downloaded and don't want to lose them, you can just replace `make.py` in your directy.

**Comment by jcontini** [comment]
This should be fixed, let me know if you run into it again
