### ISSUE TITLE
Failing to find icon element

### ISSUE THREAD

**Issue by rabimba** [jcontini/facebook-scraper#4]
Using geckodriver in Firefox in OSX.
The scripts fails to find the element

selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [data-click='profile_icon'] > a > img

Have verified that the element exists in the page.
Any idea how I can debug this?

**Comment by santteegt** [comment]
Hi @rabimba ,

What you can do is to open the Firefox dev console and test the selectors using jquery `$$`. For example you can test the element you mention with 

```
$$("[data-click='profile_icon'] > a > img")
```

I had the same issue, and I found that i need to change the selector to 
```
[data-click='profile_icon'] > a > span >img
```
With this little change, scrapping process is working again. I have sent a pull request with the single change. See  #5

**Comment by jcontini** [comment]
Hi all, I just merged the pull request so this should be fixed now. Thanks @santteegt for the fix and @rabimba for reporting! Please let me know if you're still having issues. Cheers
