### ISSUE TITLE
2nd degree connection is not working ( throwing error)

### ISSUE THREAD

**Issue by hackertron** [jcontini/facebook-scraper#7]
Hello , thanks for the script :) 

1st degree connection is working fine but when i try 2nd degree connection i get following error
###  _csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

i have not opened the csv file. i just did step 1 and then step 2.

**Comment by jcontini** [comment]
Hi @hackertron, thanks for bringing this to attention! It was a quick fix to make that part compatible with Python 3. Let me know if any more issues come up. Take care.

**Comment by hackertron** [comment]
Thanks . I am also trying to extract about section of facebook profile . Can you help with that ??

**Comment by jcontini** [comment]
@hackertron this isn't something I've tried to do yet. There's a repo at https://github.com/toxtli/facebook-profile-scraper-bot/blob/master/FacebookProfile.py that seems to have attempted this 2 years ago but I haven't tried it.

**Comment by hackertron** [comment]
Thanks !! will try it out
