### ISSUE TITLE
Unexpected EOF while parsing

### ISSUE THREAD

**Issue by steakscience** [jcontini/facebook-scraper#8]
Hi jcontini,

I seem to be running to this error after I log into Facebook and press Enter. Do you know how I can resolve this?

```
Opening browser...
Please log into facebook and press enter after the page loads...
Traceback (most recent call last):
  File "facebook-connections.py", line 132, in <module>
    fb_login()
  File "facebook-connections.py", line 19, in fb_login
    a = input("Please log into facebook and press enter after the page loads...")
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by jcontini** [comment]
Hi @SixFingeredAmish , I'm trying to replicate but unable to so far. Can you let me know what version of Python you are on? Should be Python 3

**Comment by steakscience** [comment]
@jcontini Thanks for helping out! You're right. I was using Python 2.7 which caused the error.

**Comment by Aditi96** [comment]
Hi jcontini,
I too faced the same problem and installed python3 to make this work. But it still shows the same error. How do I solve this?

**Comment by steakscience** [comment]
@Aditi96 Make sure you are actually running python 3. Run `python3 facebook-connections.py`

**Comment by Aditi96** [comment]
did that as well. Now the probelm is, I had installed anaconda thus it already has selenium installed, but running this still comes up with "ModuleNotFoundError: No module named 'selenium'". Is this because of anaconda already present or something which I am missing out?

**Comment by steakscience** [comment]
Try installing selenium through pip3

**Comment by Aditi96** [comment]
@jcontini Thanks a ton!! It worked. :)
